# Generated by Django 5.0.6 on 2024-06-06 10:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addevent',
            name='time',
        ),
        migrations.AddField(
            model_name='addevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 6, 6, 10, 16, 0, 696712, tzinfo=datetime.timezone.utc)),
        ),
    ]
