# Generated by Django 5.0.6 on 2024-06-07 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0002_remove_addevent_time_addevent_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
