# Generated by Django 5.0.6 on 2024-06-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0002_alter_attendee_registered_for'),
        ('eventApp', '0004_remove_addevent_user_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddEvent',
        ),
    ]
