# Generated by Django 5.0.6 on 2024-06-09 17:32

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0005_delete_addevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_quill.fields.QuillField(default='Enter Description'),
        ),
    ]
