# Generated by Django 5.0.6 on 2024-06-10 10:58

import django.utils.timezone
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0006_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_quill.fields.QuillField(default='Enter Your Description'),
        ),
    ]
