# Generated by Django 5.0.6 on 2024-06-07 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0001_initial'),
        ('eventApp', '0004_remove_addevent_user_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='registered_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventApp.event'),
        ),
    ]
